# Generated by Django 6.0.3 on 2026-03-19 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LoteAve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_lote', models.CharField(max_length=20, unique=True)),
                ('raza', models.CharField(max_length=100)),
                ('cantidad_actual', models.PositiveIntegerField()),
                ('fecha_ingreso', models.DateField(auto_now_add=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Lote de Ave',
                'verbose_name_plural': 'Lotes de Aves',
            },
        ),
    ]
