# Generated by Django 4.2.24 on 2026-03-19 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_lote', models.CharField(max_length=50, unique=True)),
                ('raza', models.CharField(max_length=100)),
                ('cantidad_inicial', models.IntegerField(default=0)),
                ('cantidad_actual', models.IntegerField(default=0)),
                ('cantidad_bajas', models.IntegerField(default=0)),
                ('costo_unidad', models.FloatField(default=0.0)),
                ('gastos_alimento', models.FloatField(default=0.0)),
                ('fecha_ingreso', models.DateField(auto_now_add=True)),
                ('notas', models.TextField(blank=True, null=True)),
                ('vacunado', models.BooleanField(default=False)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.DeleteModel(
            name='LoteAve',
        ),
    ]
